# Generated by Django 3.2.4 on 2021-06-30 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city_nanme',
            new_name='name',
        ),
    ]
